### ISSUE TITLE
Chevron icons get cropped while moving

### ISSUE THREAD

**Issue by alexandramfedyk** [telusdigital/tds#479] opened 2018-02-21 17:02 UTC
Description

Hover over a chevron link and look at the chevron icon. As its moving, it gets clipped. It is more pronounced in the left facing chevron.

Defect Priority: Medium
Defect Severity: Moderate
Testing Environment: Production
Method of discovery: Manual
Defect Nature: Visual

**Comment by ryanoglesby08** [comment] 2018-03-06 21:47
Unable to reproduce. Closing.

**Closed by ryanoglesby08** 2018-03-06 21:47 UTC
Labels: defect, low hanging fruit (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
